### ISSUE TITLE
Uncaught Channel closed

### ISSUE THREAD

**Issue by RenaKunisaki** [bus-stop/Termination#113]
[Enter steps to reproduce:]

1. Press Ctrl+\` to open terminal while CPU usage is high
2. Get this message upon opening and when pressing Ctrl+C in the terminal pane

**Atom**: 1.45.0 x64
**Electron**: 4.2.12
**OS**: "Arch Linux"
**Thrown From**: [termination](https://github.com/bus-stop/Termination) package 0.7.6

### Stack Trace

Uncaught Channel closed

```
At events.js:167

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:628:16)
    at Task.module.exports.Task.send (/usr/lib/atom/src/task.js:111:27)
    at TerminationView.module.exports.TerminationView.input (/packages/termination/lib/view.coffee:281:17)
    at /packages/termination/lib/view.coffee:159:8)
    at Terminal.EventEmitter.emit (/packages/termination/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/termination/node_modules/term.js/src/term.js:3493:8)
    at Terminal.keyDown (/packages/termination/node_modules/term.js/src/term.js:3196:8)
    at /packages/termination/node_modules/term.js/src/term.js:594:29)
```

### Commands

```
  2x -0:42.1.0 core:backspace (input.hidden-input)
     -0:41.4.0 autocomplete-plus:cancel (input.hidden-input)
     -0:41.1.0 intentions:highlight (input.hidden-input)
     -0:41.1.0 core:save (input.hidden-input)
     -0:40.8.0 editor:newline (input.hidden-input)
     -0:39.7.0 editor:consolidate-selections (input.hidden-input)
     -0:39.7.0 core:cancel (input.hidden-input)
     -0:30.4.0 intentions:highlight (input.hidden-input)
     -0:30.4.0 core:paste (input.hidden-input)
     -0:29.8.0 core:save (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.3.0 core:backspace (input.hidden-input)
     -0:22.8.0 intentions:highlight (input.hidden-input)
     -0:22.8.0 core:save (input.hidden-input)
     -0:16.1.0 intentions:highlight (input.hidden-input)
  2x -0:16.1.0 termination:toggle (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-lua 1.0.1 
aligner-python 1.2.0 
aligner-scss 1.3.1 
atom-smart-tabs 0.1.0 
autoclose-tags 0.2.4 
autocomplete-glsl 0.2.3 
autocomplete-lua 0.9.2 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
git-diff-plus 0.4.2 
git-plus 8.7.1 
git-time-machine 2.1.0 
intentions 1.1.5 
language-ansi 1.1.1 
language-glsl 2.0.4 
language-lua 0.9.11 
language-opencl 0.1.1 
language-powerpc-assembly 1.0.4 
linter 2.3.1 
linter-glsl 2.2.0 
linter-lua 2.0.0 
linter-python 3.1.2 
linter-ui-default 1.8.1 
python-tools 0.6.9 
semanticolor 3.6.0 
smart-tab-names 0.3.0 
sort-lines 0.19.0 
split-diff 1.6.1 
termination 0.7.6 
```

**Comment by RenaKunisaki** [comment]
After doing a system update and rebooting, the terminal pane won't open at all.

**Comment by the-j0k3r** [comment]
@RenaKunisaki there are other terminal projects you may like to try, see https://github.com/bus-stop
