### ISSUE TITLE
[BR] Apm install failed

### ISSUE THREAD

**Issue by AirKetchPLAYZ** [bus-stop/Termination#114]
- [ ] I have reset Atom to defaults prior to submitting report.
- [X] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [X] I have not tried uninstalling/reinstalling the terminal.
### Steps to reproduce

1. Have atom installed
2. apm install termination

**Expected behavior:**
It installs normally

**Actual behavior:**
It fails with this error:
```
> node-pty-prebuilt-multiarch@0.9.0 install /tmp/apm-install-dir-120520-9401-1fqrcwk.h8fwj/node_modules/termination/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.4.0-7634-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120520-9401-1fqrcwk.h8fwj/node_modules/termination/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120520-9401-1fqrcwk.h8fwj/package.json'
npm WARN apm-install-dir-120520-9401-1fqrcwk.h8fwj No description
npm WARN apm-install-dir-120520-9401-1fqrcwk.h8fwj No repository field.
npm WARN apm-install-dir-120520-9401-1fqrcwk.h8fwj No README data
npm WARN apm-install-dir-120520-9401-1fqrcwk.h8fwj No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Reproduces how often:**
Always

### Versions

```
> atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.18rc1
git 2.25.1
```
OS name and version: Pop!_Os 20.04 (basicly ubuntu 20.04 with extra drivers and combined with elementary OS app store)

### Additional context
Community Packages (6) /home/joshualausch/.atom/packages
├── autocomplete-clang@0.13.1
├── build@0.70.0
├── build-make@0.13.0
├── busy-signal@2.0.1
├── dbclick-tree-view@1.6.3
└── npm-install@4.0.4

**Comment by the-j0k3r** [comment]
Its an APM issue not the terminal. The repo for APM is https://github.com/atom/apm/issues  probably already open issues havent checked.
