### ISSUE TITLE
Uncaught Error: Cannot find module './input-dialog'Require stack:- $ATOM_HOME/packages\terminat...

### ISSUE THREAD

**Issue by zeynepkiymik** [bus-stop/Termination#121]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [termination](https://github.com/bus-stop/Termination) package 0.7.6

### Stack Trace

Uncaught Error: Cannot find module './input-dialog'
Require stack:
- C:\Users\zynpk\.atom\packages\termination\lib\view.coffee
- C:\Users\zynpk\.atom\packages\termination\lib\status-bar.coffee
- C:\Users\zynpk\.atom\packages\termination\lib\termination.coffee
- C:\Users\zynpk\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module './input-dialog'
Require stack:
- C:\Users\zynpk\.atom\packages\termination\lib\view.coffee
- C:\Users\zynpk\.atom\packages\termination\lib\status-bar.coffee
- C:\Users\zynpk\.atom\packages\termination\lib\termination.coffee
- C:\Users\zynpk\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at TerminationView.module.exports.TerminationView.inputDialog (/packages/termination/lib/view.coffee:810:23)
    at /packages/termination/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/termination/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/termination/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:30 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
termination 0.7.6 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, the gremlins, =)

1. Close Atom (all instances)
1. Remove `~/.atom/packages/termination`
1. run on an external terminal `apm install termination`
1. Open Atom profit

It works otherwise in all OS's with sane Atom installs
