### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'Require stack:- $ATOM_HOME/packages\termination...

### ISSUE THREAD

**Issue by mertkaan33** [bus-stop/Termination#122]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [termination](https://github.com/bus-stop/Termination) package 0.7.6

### Stack Trace

Uncaught Error: Cannot find module '../src/term'
Require stack:
- C:\Users\necat\.atom\packages\termination\node_modules\term.js\lib\index.js
- C:\Users\necat\.atom\packages\termination\node_modules\term.js\index.js
- C:\Users\necat\.atom\packages\termination\lib\view.coffee
- C:\Users\necat\.atom\packages\termination\lib\status-bar.coffee
- C:\Users\necat\.atom\packages\termination\lib\termination.coffee
- C:\Users\necat\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module '../src/term'
Require stack:
- C:\Users\necat\.atom\packages\termination\node_modules\term.js\lib\index.js
- C:\Users\necat\.atom\packages\termination\node_modules\term.js\index.js
- C:\Users\necat\.atom\packages\termination\lib\view.coffee
- C:\Users\necat\.atom\packages\termination\lib\status-bar.coffee
- C:\Users\necat\.atom\packages\termination\lib\termination.coffee
- C:\Users\necat\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at Function.Terminal (/packages/termination/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.TerminationView.getFocusedTerminal (/packages/termination/lib/view.coffee:119:23)
    at /packages/termination/lib/status-bar.coffee:364:42
```

### Commands

```
  2x -9:55 core:copy (input.hidden-input)
     -9:52.8.0 core:select-all (input.hidden-input)
     -9:50 core:backspace (input.hidden-input)
     -9:25.7.0 core:select-all (input.hidden-input)
     -9:25.3.0 core:copy (input.hidden-input)
     -9:23.6.0 core:select-all (input.hidden-input)
     -9:23.5.0 core:paste (input.hidden-input)
     -7:09.1.0 core:select-all (input.hidden-input)
     -7:08.9.0 core:copy (input.hidden-input)
     -7:07.5.0 core:select-all (input.hidden-input)
     -7:07.3.0 core:paste (input.hidden-input)
     -3:20.9.0 core:backspace (input.hidden-input)
     -3:20.5.0 core:delete (input.hidden-input)
     -3:07.8.0 core:select-all (input.hidden-input)
     -3:07.6.0 core:cut (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 2.0.2 
dracula-syntax 3.0.2 
dracula-ui 0.6.0 
language-disco 0.3.1 
termination 0.7.6 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, the gremlins, =)

1. Close Atom (all instances)
1. Remove `~/.atom/packages/termination`
1. run on an external terminal `apm install termination`
1. Open Atom profit
